create table if not exists public.card_labels (id bigint generated by default as identity primary key,name text not null unique,color text not null default '#d8ff3e',created_at timestamptz not null default now());
alter table public.card_labels enable row level security;
create policy "Public can read card labels" on public.card_labels for select to anon, authenticated using (true);
alter table public.cards add column if not exists label_id bigint references public.card_labels(id) on delete set null;
insert into public.card_labels (name,color) values ('New','#d8ff3e') on conflict (name) do nothing;
