create table if not exists public.wanted_cards (
  id bigint generated by default as identity primary key,
  title text not null,
  category_id bigint not null references public.categories(id) on delete restrict,
  details text not null default '',
  priority text not null default 'Open to offers',
  tone text not null default 'purple',
  status text not null default 'active' check (status in ('active', 'draft')),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists wanted_cards_status_idx on public.wanted_cards(status, sort_order);
alter table public.wanted_cards enable row level security;

create policy "Public can read active wanted cards"
  on public.wanted_cards for select
  to anon, authenticated
  using (status = 'active');
