alter table public.cards drop constraint if exists cards_status_check;

create table if not exists public.card_options (
  id bigint generated by default as identity primary key,
  option_type text not null check (option_type in ('status', 'condition')),
  label text not null,
  value text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (option_type, value)
);

alter table public.card_options enable row level security;

insert into public.card_options (option_type, label, value, sort_order)
values
  ('status', 'Active', 'active', 10),
  ('status', 'Draft', 'draft', 20),
  ('status', 'Sold', 'sold', 30),
  ('condition', 'Mint', 'Mint', 10),
  ('condition', 'Near mint', 'Near mint', 20),
  ('condition', 'Excellent', 'Excellent', 30),
  ('condition', 'Good', 'Good', 40),
  ('condition', 'Played', 'Played', 50)
on conflict (option_type, value) do nothing;
