create table if not exists public.cms_users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users(id) on delete set null,
  email text not null unique,
  name text not null,
  role text not null default 'editor' check (role in ('owner', 'admin', 'editor')),
  status text not null default 'active' check (status in ('active', 'invited', 'disabled')),
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  accent text not null default '#d8ff3e',
  created_at timestamptz not null default now()
);

create table if not exists public.cards (
  id bigint generated by default as identity primary key,
  title text not null,
  category_id bigint not null references public.categories(id) on delete restrict,
  card_code text not null default '',
  image_key text,
  price_cents integer not null default 0 check (price_cents >= 0),
  stock integer not null default 0 check (stock >= 0),
  condition text not null default 'Near mint',
  status text not null default 'active' check (status in ('active', 'draft', 'sold')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists cards_category_idx on public.cards(category_id);
create index if not exists cards_status_idx on public.cards(status);

alter table public.cms_users enable row level security;
alter table public.categories enable row level security;
alter table public.cards enable row level security;

create policy "Public can read categories"
  on public.categories for select
  to anon, authenticated
  using (true);

create policy "Public can read active cards"
  on public.cards for select
  to anon, authenticated
  using (status = 'active');

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'card-images',
  'card-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "Public can view card images"
  on storage.objects for select
  to public
  using (bucket_id = 'card-images');
